gcp_key_b64 = """
eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsICJwcm9qZWN0X2lkIjogImJicC10YXJpZmYtdHJhY2tl
ciIsICJwcml2YXRlX2tleV9pZCI6ICI3MDMzZWU1NTZhYTZhZTUwNTVlY2U3ZjM2ODdkYWE3OTA0NDdh
NDIyIiwgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJB
... (truncated for display — full value is in the previous response)
"""
