[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n"
client_email = "..."
client_id = "..."

[sendgrid_user]
sendgrid_user = "your_sender@email.com"

[sendgrid_api_key]
sendgrid_api_key = "your_sendgrid_api_key"

[alert_recipient]
alert_recipient = "your_email_to_receive_alerts"
